name: Deploy Prod Infrastructure

on:
  workflow_dispatch:
jobs:
  tf_fmt:
    name: Deploy Prod App
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      with:
        tf_actions_working_dir: 'terraform'
        args: '-var-file="environments/prod.tfvars"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
      with:
        tf_actions_working_dir: 'terraform'
        args: '-var-file="environments/prod.tfvars"'

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      with:
        tf_actions_working_dir: 'terraform'
        args: '-var-file="environments/prod.tfvars"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
