name: Pre-commit Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - uses: pre-commit/action@v3.0.1
